### ISSUE TITLE
Runtime - Stuck(?) on Rule Sequence merge

### ISSUE THREAD

**Issue by stachyris** [TurakhiaLab/ROADIES#21] opened 2024-06-06 23:14 UTC
Hi, 
Please see the attached screenshot. 

I have been trying to run ROADIES on 10 genomes of approx ~1.2GB size, but it seems like it's been stuck on the sequence merge step for a few hours.  Hasn't thrown any error yet - but no output as well. CPU usage is zero. 
So, I was wondering if you would advise on keeping it running or not. 

All default settings in config.yaml and the roadies_env have no issues. 

``python run_roadies.py --cores 16 --mode accurate`` is the used command. 

PS: Time in the screenshot is IST. 

Thank you, and I am looking forward to your comment. 

<img width="1470" alt="Screenshot 2024-06-06 at 6 01 41 PM" src="https://github.com/TurakhiaLab/ROADIES/assets/61734552/3ae118ec-267d-425b-aa91-b2214962f5e6">

**Comment by stachyris** [comment] 2024-06-10 17:05
Process killed after 4 days without any further progress. Plots directory has 'sampling.csv' though. 
Any suggestions for tweaks that could help in a re-run?

**Comment by stachyris** [comment] 2024-06-10 17:06
Process killed after 4 days without any further progress. Plots directory has 'sampling.csv' though. 
Any suggestions for tweaks that could help in a re-run?

**Comment by ang037** [comment] 2024-06-11 19:48
Hi. Apologies for the delayed response. Could you please send us your `config.yaml` file and also the log file for the snakemake run (you can find the log file in the directory `ROADIES/.snakemake/log/` )?

**Comment by stachyris** [comment] 2024-06-11 20:59
Hi, No worries. Have attached the log file and for some reason I could not upload the config file hence pasting the parameters as text. 


#This file configures the parameters for ROADIES

#Path for input genomes
GENOMES: "/mnt/d/Vinay/turdus_genome_tree/assemblies"
#Reference tree (optional, default set as null)
REFERENCE: NULL
#Length of each of the genes
LENGTH: 500
#Number of genes per iteration
GENE_COUNT: 250
#Minimum % uppercase for sampling valid genes
UPPER_CASE: 0.90
#ROADIES output directory (current iteration output in --converge option)
OUT_DIR: "turdus_roadies"
#ROADIES output directory for all iterations (only used in --converge option)
ALL_OUT_DIR: "converge_files"
#Minimum number of species in a gene fasta (4 min for ASTRAL-Pro)
MIN_ALIGN: 4 
#Minimum % match in LASTZ alignment
IDENTITY: 65
#Minimum input sequence coverage in LASTZ alignment
COVERAGE: 85
#Minimum continuity of LASTZ alignments
CONTINUITY: 85
#Max number of gene copies from a genome in an alignment
MAX_DUP: 10
#Number of steps in LASTZ sampling
STEPS: 1
#PASTA filtering parameters
FILTERFRAGMENTS: 0.50

[2024-06-06T233855.405809.snakemake.log](https://github.com/user-attachments/files/15794705/2024-06-06T233855.405809.snakemake.log)

**Comment by ang037** [comment] 2024-06-18 19:35
Hi. I was not able to reproduce the issue from my side. This seems weird, as your config.yaml file also looks correct. Could you check if your system supports 16 cores or threads in parallel, and maybe try rerunning the pipeline again? Please let me know if you still face the same issue. 

Also, do you provide these parameters as well (missing in the pasted text above)? 
MASKSITES: 0.02
#Threshold for high support (only used in --converge option)
SUPPORT_THRESHOLD: 0.95
#Number of instances to run in parallel
NUM_INSTANCES: 4

**Comment by stachyris** [comment] 2024-06-19 21:13
Hi, 
I figured it out - for some reason, if the input files are on an external mount, it gets stuck. I moved the input assemblies within ROADIES directory ( like for the test dataset) it completed the analysis. 

Thanks again, 
Vinay

**Comment by ang037** [comment] 2024-06-20 16:15
Glad that it worked for you. 
Additionally, we checked ROADIES with genomes saved in externally mounted volume, and it worked for us. Genome files do not necessarily need to be saved within the ROADIES directory. You may want to check if there are any system-related constraints.

I am closing this issue now. Let us know if you need further assistance from our side. Thanks for your input.

**Closed by ang037** 2024-06-20 16:15 UTC
